name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - run: yarn --immutable
      - run: yarn build
      - run: yarn test
      - run: yarn prettier:check
      - run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
